version: "3"
services:
    fastapi:
        build: .
        ports: 
            - "8000:8000"
        depends_on:
          - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 123gr
            POSTGRES_DB: social_app
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - default
volumes:
    postgres_data: